---
- name: Build /etc/hosts
  hosts: all
  tasks:
    - name: Print Facts
      ansible.builtin.debug: 
        var: ansible_facts
    - name: Print specific fact
      ansible.builtin.debug:
        msg: "Default Networking Information is {{ ansible_facts.default_ipv4.address }}\n"

    # change eth0 name to enp1s0 in RHEL v10
    - name: Print from specific adapter
      ansible.builtin.debug: 
        msg: >
          The IP Address for eth0 is {{ ansible_facts.enp1s0.ipv4.address }}
          the FQDN is  {{ ansible_facts.fqdn }} and the hostname is  {{ ansible_facts.hostname }}

    # change eth0 name to enp1s0 in RHEL v10
    - name: Print using hostvars
      ansible.builtin.debug:
        msg: >
          The hostvars for IP address is {{ hostvars[inventory_hostname]['ansible_facts']['enp1s0']['ipv4']['address'] }}
          and the FQDN is {{ hostvars[inventory_hostname]['ansible_facts']['fqdn'] }}
          and the hostname is {{ hostvars[inventory_hostname]['ansible_facts']['hostname'] }}

    - name: deploy template
      ansible.builtin.template:
        src: etc_hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
        setype: net_conf_t
