---
- name: Install Services and Packages to managed systems
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest
- name: Start Services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ services }}"
