
---
- name: Install and start Apache HTTPD
  hosts: web
  tasks:
    - name: httpd package is present
      ansible.builtin.yum:
        name:
          - httpd
          - firewalld
        state: absent


